# Project: Prcatica 10
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Practica15.o
LINKOBJ  = Practica15.o
LIBS     = -L"C:/Users/range/OneDrive/Escritorio/Dev-Cpp/MinGW64/lib" -L"C:/Users/range/OneDrive/Escritorio/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/range/OneDrive/Escritorio/Dev-Cpp/MinGW64/include" -I"C:/Users/range/OneDrive/Escritorio/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/range/OneDrive/Escritorio/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/range/OneDrive/Escritorio/Dev-Cpp/MinGW64/include" -I"C:/Users/range/OneDrive/Escritorio/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/range/OneDrive/Escritorio/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/range/OneDrive/Escritorio/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = "Prcatica 10.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Practica15.o: Practica15.cpp
	$(CPP) -c Practica15.cpp -o Practica15.o $(CXXFLAGS)
